server:
  port: 8090   #default port where the service will be started

eureka:         #tells about the Eureka server details and its refresh time
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
    healthcheck:
      enabled: false
    lease:
      duration: 5

spring:
  application:
    name: student-service   #current service name to be used by the eureka server
  data.mongodb.uri: mongodb://localhost:27017/project

#management:
#  security:
#    enabled: false  #disable the spring security on the management endpoints like /env, /refresh etc.

logging:
  level:
    com.example.howtodoinjava: DEBUG