server:
  port: 9091    #port number

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2

  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

spring:
  application:
    name: school-service
  datasource:
      url: jdbc:postgresql://localhost:5432/project
      username: postgres
      password: root
      driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
        ddl-auto: update
logging:
  level:
    com.example.howtodoinjava: DEBUG

